config/routes.rb
Sanisurvey::Application.routes.draw do
root to: 'surveys#index'
  resources :surveys
  resources :users
  resources :customers do
    collection { post :import }
  end  
  
  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :image
  # attr_accessible :title, :body
  has_many :surveys
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :contact_name, :customer_number, :email, :phone, :postal_code, :province, :restaurant_name, :street_address, :city
  has_many :surveys

  after_create :create_survey

  def self.to_csv(options = {})
  	CSV.generate(options) do |csv|
  		csv << column_names
  		all.each do |customer|
  			csv << customer.attributes.values_at(*column_names)
  		end
  	end
  end		

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
    when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
    when '.xlsx' then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      customers = find_by_id(row["id"]) || new
      customers.attributes = row.to_hash.slice(*accessible_attributes)
      customers.save!
    end
  end
  
  def create_survey
    self.surveys.create    
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :capac_of_fryer, :chicken_fat, :comments_equip, :comments_recupe, :customer_id, :date, :desired_location, :desired_map, :freq_of_disposal, :grease_trap_service, :grill_plate, :install_electicity_outside, :integrated_solution, :kind_of_oil, :location, :location_map, :number_of_fryers, :organic_pu, :outdoor_electricity, :present_equip, :suggested_equip, :user_id, :image
  
  belongs_to :admin
  belongs_to :customer
  has_attached_file :image, 
    :styles => { :medium => "160x160>", :thumb => "180x180>", :large => "660x660>" }, 
    :default_url => "/images/:style/missing.png",
    :storage => :s3, s3_credentials: {access_key_id: "AKIAJQFILE7GM3P4IOUA",
    secret_access_key: "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",
    bucket: "surveymax"} 




  # def self.to_csv(options = {})
    	# CSV.generate(options) do |csv|
    	# 	csv << column_names
    	# 	all.each do |survey|
    	# 		csv << survey.attributes.values_at(*column_names)
    	# 	end
    	# end
  # end		


  def self.to_csv(options = {})
    #s = Survey.find(:all, :joins => :customer, :select => ['surveys.id', :customer_id, :restaurant_name])
    s = Survey.find(:all, :joins => :customer, :select => 'customer_number, restaurant_name, city, surveys.*')

    columns_headings = ["customer_number", "restaurant_name", "city"] + Survey.column_names
    #columns_headings = columns_headings - ['customer_id']

    CSV.generate(options) do |csv|
      csv << columns_headings
      s.each do |survey|
        csv << survey.attributes.values_at(*columns_headings)
      end
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :fullname
  has_many :surveys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_admin!

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.order(:customer_number)
    respond_to do |format|
    format.html
    format.csv { send_data @customers.to_csv }
    format.xls { send_data @customers.to_csv(col_sep: "\t") }
    end  
	end
  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end
	def new
      @customer = customer.new
  end

  def import
    Customer.import(params[:file])
    redirect_to customers_path, notice: "Customers"
  end

  def edit
    @customer = Customer.find(params[:id])
  end

    def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

    def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

    # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def index
		@surveys = Survey.order(:id)
		respond_to do |format|
	    format.html
	    format.csv { send_data Survey.to_csv }
	    format.xls { send_data @surveys.to_csv(col_sep: "\t") }
	    end  
	end

	def new
      @survey = Survey.new
    end
  
    def create
    @survey = Survey.new(params[:survey])
	
	  respond_to do |format|    
	    if @survey.save
	      	format.html { redirect_to surveys_path, notice: 'survey was successfully updated.' }
	        format.json { head :no_content } 
	    else
	      # This line overrides the default rendering behavior, which
	      # would have been to render the "create" view.
	       format.html { render action: "new" }
	       format.json { render json: @survey.errors, status: :unprocessable_entity }
	    end
	  end
	end

	def show
		@survey = Survey.find(params[:id])
	end

	def edit
	  @survey = Survey.find(params[:id])
    end

    def update
	    @survey = Survey.find(params[:id])

	    respond_to do |format|
	      if @survey.update_attributes(params[:survey])
	        format.html { redirect_to @survey, notice: 'survey was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: "edit" }
	        format.json { render json: @survey.errors, status: :unprocessable_entity }
	      end
	    end
	end
    def destroy
	    @survey = Survey.find(params[:id])
	    @survey.destroy

	    respond_to do |format|
	      format.html { redirect_to survey_url }
	      format.json { head :no_content }
    end
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customers</h2>

<p>
  Download to Excel:
  <%= link_to "CSV", customers_path(format: "csv") %>
  <%= link_to "Excel", customers_path(format: "xls") %>
</p>


<table class="display" id="customers">
 <thead> 
  <tr>
    <th>Survey</th>
  	<th>Customer Number</th>
   	<th>Restaurant Name</th>
  	<th>Street Address</th>
  	<th>City</th>
  	<th>Postal Code</th>
  	<th>Province</th>
  	<th>Phone</th>
  	<th>Email</th>
  	<th>Contact Name</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
 </thead>
 <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= link_to "Survey", edit_survey_path(customer.surveys.first.id) if customer.surveys.first %></td>
    	<td><%= customer.customer_number %></td>
     	<td><%= customer.restaurant_name %></td>
    	<td><%= customer.street_address %></td>
    	<td><%= customer.city %></td>
    	<td><%= customer.postal_code %></td>
    	<td><%= customer.province %></td>
    	<td><%= customer.phone %></td>
    	<td><%= customer.email %></td>
    	<td><%= customer.contact_name %></td>
      <td><%= link_to 'Show', customer %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>  
</table>

<%= form_tag import_customers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= link_to 'Back', customers_path %>

app/views/customers/index.xls.erb

<table class="table table-striped table-condensed" id="customers">
  <tr>
  	<th>Customer Number</th>
   	<th>Restaurant Name</th>
  	<th>Street Address</th>
  	<th>City</th>
  	<th>Postal Code</th>
  	<th>Province</th>
  	<th>Phone</th>
  	<th>Email</th>
  	<th>Contact Name</th>
    <th>Details</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
  	<td><%= customer.customer_number %></td>
   	<td><%= customer.restaurant_name %></td>
  	<td><%= customer.street_address %></td>
  	<td><%= customer.city %></td>
  	<td><%= customer.postal_code %></td>
  	<td><%= customer.province %></td>
  	<td><%= customer.phone %></td>
  	<td><%= customer.email %></td>
  	<td><%= customer.contact_name %></td>
  </tr>
<% end %>  
</table>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer number:</b>
  <%= @customer.customer_number %>
</p>

<p>
  <b>Restaurant name:</b>
  <%= @customer.restaurant_name %>
</p>

<p>
  <b>Street address:</b>
  <%= @customer.street_address %>
</p>

<p>
  <b>Postal code:</b>
  <%= @customer.postal_code %>
</p>

<p>
  <b>Province:</b>
  <%= @customer.province %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Contact name:</b>
  <%= @customer.contact_name %>
</p>

<p>
  <b>City:</b>
  <%= @customer.city %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sanisurvey</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <script src="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" />
</head>
<body class="body">
	<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                    </button><a class="brand" href="#"><%= image_tag("surveymax.png", :alt => "surveymax") %></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav fun">
                            <li><a href="#">Home</a>
                            </li>
                            <li class="active"><a href="https://s3.amazonaws.com/surveymax/Template/upload_template.csv"><i class="icon-file icon-white"></i>Excel Template</a>
                            </li>
                            <li>                          	
                            	<% if admin_signed_in? %>
									  
									  	<%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
									  
									<% else %>
								  		
								 		 <%= link_to('Login', new_admin_session_path)  %>  
								  		
								<% end %>
								
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

<%= yield %>

</body>
</html>

app/views/surveys/_form.html.erb
<%= semantic_form_for @survey, html: {multipart: true} do |f| %>


    <%= f.inputs "Questions", :id => "questions" do %>
      <%= f.input :location_map, :label => "Customer Decision", :as => :select, :collection => ["Accepted", "Delclined", "Rep Action"] %>
      <%= f.input :kind_of_oil, :label => "Which kind of oil is used? (Vegetable or Shortening)", :as => :radio, :collection => ["Vegetable Oil", "Shortening"]  %>
      <%= f.input :grill_plate, :label => "Do you dump your leftovers in the container?", :as => :radio, :collection => ["Yes", "No"]  %>
      <%= f.input :chicken_fat, :label => "Do you dump your chicken fat in the container", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :grease_trap_service, :label => "Do you use a grease trap emptying service", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :outdoor_electricity, :label => "Do you have an electrical outlet outside (Dedicated, GFI & min.15A)", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :install_electicity_outside, :label => "If not, would you be willing to install one?", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :present_equip, :label => "Equipment type currently used", :as => :select, :collection => ["Barrel", "Onken", "Heated Tank", "Sanicart", "Underground Tank", "Other"] %>
      <%= f.input :number_of_fryers, :label => "Number of fryers used" %>
      <%= f.input :capac_of_fryer, :label => "Capacity of each fryer (kgs)" %>
      <%= f.input :freq_of_disposal, :label => "How often do you change the fryers (days)" %>
      <%= f.input :suggested_equip, :label => "What equipment do you suggest?", :as => :select, :collection => ["Small tank", "Med tank","Lrg tank", "Small heated tank ", "Med heated tank","Lrg heated tank"] %>
      <% end %>

    <%= f.inputs "Current Location of the equipment for cooking oil recovery", :id => "equipment_images" do %>
      <%= f.input :image, :as => :file, :label => "Ideal picture of area" %>
    <% end %>

    <%= f.inputs "Desired Location of the equipment for cooking oil recovery", :id => "equipment_images_desired" do %>
      <%= f.input :desired_location, :label => "Schematic drawing of area or google map screenshot" %>
      <%= f.input :image, :as => :file, :label => "Nice picture of area" %>
    <% end %>

    <%= f.inputs "Final questions", :id => "final_questions" do %>
      <%= f.input :integrated_solution, :label => "Would you be interested in an integrated solution for your cooking oil recovery?", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :organic_pu, :label => "Would you be interested in an organic waste collection service?", :as => :radio, :collection => ["Yes", "No"] %>
      <%= f.input :comments_equip, :label => "Equipment comments" %>
      <%= f.input :comments_recupe, :label => "Recuperation" %>
    <% end %>

    <%= f.actions do %>
      <%= f.action :submit, :as => :button %>
      <%= f.action :cancel, :as => :link %>
    <% end %>
<% end %>
<%= link_to 'Back', surveys_path %>

app/views/surveys/edit.html.erb
<h1>Editing Surveys</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p>
  Download to Excel:
  <%= link_to "CSV", surveys_path(format: "csv") %>
  <%= link_to "Excel", surveys_path(format: "xls") %>
</p>
<div class="dataTables_wrapper" role="grid">
  <div class="dataTables_scrollBody" style="width: 100%; overflow: auto;">
    <table class="display" id="customers">
     <thead>
      <tr>
        <th>Customer Number</th>
        <th>Customer Name</th>
        <th>Customer Address</th>
        <th>Customer City</th>
        <th>Customer Decision</th>
        <th>Oil Type</th>
        <th>Collect Grill Scrapings?</th>
        <th>Collect Grill Fat?</th>
        <th>Grease Trap Service</th>
        <th>Outdoor Elec?</th>
        <th>Want Outdoor Elec?</th>
        <th>Present Equip?</th>
        <th># of Fryers</th>
        <th>Fryer Capac (kgs)</th>
        <th>Frq Disposal (in days)</th>
        <th>Suggested Equip</th>
        <th>Location image</th>
        <th>desired Location image</th>
        <th>desired Location map </th>
        <th>Want integrated solution?</th>
        <th>Want organic p/u?</th>
        <th>Comments on Equipment</th>
        <th>Comments on recuperation</th>
        <th>Customer Id</th>
        <th>Admin_id</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>  
    </thead>

    <tbody>
    <% @surveys.each do |p| %>
      <tr>
        <% if p.customer %>
          <td><%= p.customer.customer_number if p.customer %></td>
          <td><%= p.customer.restaurant_name if p.customer %></td>
          <td><%= p.customer.street_address if p.customer %></td>
          <td><%= p.customer.city if p.customer %></td>
        <% else %>
          <td>This survey id: <%= p.id  %> has an invalid customer number.</td>
          <td>N/A</td>
          <td>N/A</td>
          <td>N/A</td>
        <% end %>
        <td><%= p.location_map %></td>
        <td><%= p.kind_of_oil %></td>
        <td><%= p.grill_plate %></td>
        <td><%= p.chicken_fat %></td>
        <td><%= p.grease_trap_service %></td>
        <td><%= p.outdoor_electricity %></td>
        <td><%= p.install_electicity_outside %></td>
        <td><%= p.present_equip %></td>
        <td><%= p.number_of_fryers %></td>
        <td><%= p.capac_of_fryer %></td>
        <td><%= p.freq_of_disposal %></td>
        <td><%= p.suggested_equip %></td>
        <td><%= image_tag p.image.url(:thumb) %></td>
        <td><%= p.desired_location %></td>
        <td><%= image_tag p.image.url(:thumb) %></td>
        <td><%= p.integrated_solution %></td>
        <td><%= p.organic_pu %></td>
        <td><%= p.comments_equip %></td>
        <td><%= p.comments_recupe %></td>
        <td><%= p.customer_id %></td>
        <td><%= p.user_id %></td>
        <td><%= link_to 'Show', p %></td>
        <td><%= link_to 'Edit', edit_survey_path(p) %></td>
        <td><%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>           

    <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>


app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer Number</b>
  <%= @survey.customer.customer_number %>
</p>
<p>
  <b>Restaurant Name</b>
  <%= @survey.customer.restaurant_name %>
</p>
<p>
  <b>Street address</b>
  <%= @survey.customer.street_address %>
</p>
<p>
  <b>City</b>
  <%= @survey.customer.city %>
</p>

<p>
  <b>Customer</b>
  <%= @survey.location_map %>
</p>

<p>
  <b>What type of oil is it?</b>
  <%= @survey.kind_of_oil %>
</p>

<p>
  <b>Do you collect leftovers from the grill plate?</b>
  <%= @survey.grill_plate %>
</p>

<p>
  <b>Do you collect the chicken fat?</b>
  <%= @survey.chicken_fat %>
</p>

<p>
  <b>Do you currently have a grease trap service?</b>
  <%= @survey.grease_trap_service %>
</p>

<p>
  <b>Do you have access to outdoor electricity?</b>
  <%= @survey.outdoor_electricity %>
</p>

<p>
  <b>If not, would you be willing to install some?</b>
  <%= @survey.install_electicity_outside %>
</p>

<p>
  <b>What kind of equipment do you have currently?</b>
  <%= @survey.present_equip %>
</p>

<p>
  <b>How many fryers do you have?</b>
  <%= @survey.number_of_fryers %>
</p>

<p>
  <b>What is the capacity of each fryer (kgs) ?</b>
  <%= @survey.capac_of_fryer %>
</p>

<p>
  <b>How often do you dispose your grease (in days)</b>
  <%= @survey.freq_of_disposal %>
</p>

<p>
  <b>What equipment do you suggest?</b>
  <%= @survey.suggested_equip %>
</p>

<p>
  <b>Current location of equipment (image)</b>
  <%= image_tag @survey.image %>
</p>

<p>
  <b>Desired location of equipment (image)</b>
  <%= image_tag @survey.image %>
</p>

<p>
  <b>Desired spot on map screenshot</b>
  <%= @survey._desired_map %>
</p>

<p>
  <b>Are you interested in an integrated solution?</b>
  <%= @survey.integrated_solution %>
</p>

<p>
  <b>Are you interested in organic pick up?</b>
  <%= @survey.organic_pu %>
</p>

<p>
  <b>Comments on Equipment?</b>
  <%= @survey.comments_equip %>
</p>

<p>
  <b>Comments on recuperation?</b>
  <%= @survey.comments_recupe %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>


   